language: minimal

addons:
  apt:
    packages:
      - luarocks

install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"

# branches:
#   only:
#   - /^\d+\.\d+(\.\d+)?(-\S*)?$/

script:
  - curl -s https://raw.githubusercontent.com/Wutname1/packager/master/release.sh | bash
  - curl -s https://raw.githubusercontent.com/Wutname1/packager/master/release.sh | bash -s -- -g 1.13.2

notifications:
  email:
    on_failure: always
    on_success: always
